// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5c690557-04fe-4835-a92a-0e48342cb273";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDemoScenarioChange();
void onAlarmEnabledChange();
void onCapturePhotoChange();
void onDemoModeChange();
void onResetAlarmChange();
void onSosAdultChange();
void onSosChildChange();

String alarm_status;
String email_event_type;
String email_sent_status;
String last_event;
String last_event_type;
String last_unknown_mac;
String photo_status;
String rfid_uid;
String sos_message;
float kitchen_temperature;
float ultrasonic_distance;
int demo_scenario;
int event_counter;
int flame_value;
int ldr_value;
int sos_level;
int threat_level;
int unknown_wifi_count;
bool access_status;
bool alarm_enabled;
bool buzzer_on;
bool capture_photo;
bool demo_mode;
bool fire_alert;
bool flame_detected;
bool intrusion_alert;
bool known_device_present;
bool led_red_on;
bool pet_detected;
bool pir_detected;
bool reset_alarm;
bool rfid_authorized;
bool sabotage_alert;
bool send_email_request;
bool sos_adult;
bool sos_child;
bool system_armed;
bool unknown_wifi_alert;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(alarm_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(email_event_type, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(email_sent_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_event, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_event_type, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_unknown_mac, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photo_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rfid_uid, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sos_message, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(kitchen_temperature, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(ultrasonic_distance, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(demo_scenario, READWRITE, ON_CHANGE, onDemoScenarioChange);
  ArduinoCloud.addProperty(event_counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(flame_value, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(ldr_value, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(sos_level, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(threat_level, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(unknown_wifi_count, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(access_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarm_enabled, READWRITE, ON_CHANGE, onAlarmEnabledChange);
  ArduinoCloud.addProperty(buzzer_on, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(capture_photo, READWRITE, ON_CHANGE, onCapturePhotoChange);
  ArduinoCloud.addProperty(demo_mode, READWRITE, ON_CHANGE, onDemoModeChange);
  ArduinoCloud.addProperty(fire_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(flame_detected, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(intrusion_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(known_device_present, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_red_on, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pet_detected, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pir_detected, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(reset_alarm, READWRITE, ON_CHANGE, onResetAlarmChange);
  ArduinoCloud.addProperty(rfid_authorized, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sabotage_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(send_email_request, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sos_adult, READWRITE, ON_CHANGE, onSosAdultChange);
  ArduinoCloud.addProperty(sos_child, READWRITE, ON_CHANGE, onSosChildChange);
  ArduinoCloud.addProperty(system_armed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(unknown_wifi_alert, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
