// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "20c65f7e-3a23-4472-8634-3df4df3e8a76";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSosAuthorityNoteChange();
void onAutoArmHourChange();
void onAutoArmMinuteChange();
void onAutoDisarmHourChange();
void onAutoDisarmMinuteChange();
void onDemoScenarioChange();
void onRearmDelaySecondsChange();
void onSensitivityLevelChange();
void onAlarmEnabledChange();
void onDemoModeChange();
void onKnownDevicePresentChange();
void onManualCapturePhotoChange();
void onResetAlarmChange();
void onScheduleEnabledChange();
void onSosAdultChange();
void onSosChildChange();
void onTrustedBleDetectionEnabledChange();
void onUnknownWifiDetectionEnabledChange();

String alarm_status;
String current_time;
String device_health_status;
String emergency_authority_message_status;
String emergency_escalation_status;
String heartbeat_status;
String last_alert_time;
String last_event;
String last_event_type;
String last_heartbeat_time;
String last_unknown_mac;
String notification_channel;
String notification_event_type;
String notification_sent_status;
String photo_status;
String sos_authority_note;
String sos_message;
String trusted_device_source;
float ultrasonic_distance;
int auto_arm_hour;
int auto_arm_minute;
int auto_disarm_hour;
int auto_disarm_minute;
int current_hour;
int demo_scenario;
int event_counter;
int intrusion_score;
int ldr_delta;
int ldr_value;
int rearm_countdown_remaining;
int rearm_delay_seconds;
int sensitivity_level;
int threat_level;
int trusted_ble_last_seen_seconds;
int trusted_ble_rssi;
int unknown_wifi_count;
bool alarm_enabled;
bool auto_capture_photo_request;
bool buzzer_on;
bool cooldown_active;
bool critical_security_compromise;
bool demo_mode;
bool device_tampered;
bool emergency_confirmation_requested;
bool emergency_confirmed;
bool home_address_configured;
bool intrusion_alert;
bool known_device_present;
bool ldr_covered;
bool led_green_on;
bool led_red_on;
bool light_abnormal;
bool manual_capture_photo;
bool night_mode;
bool object_near;
bool pet_detected;
bool pir_detected;
bool reset_alarm;
bool sabotage_alert;
bool schedule_enabled;
bool send_notification_request;
bool sos_adult;
bool sos_child;
bool system_armed;
bool trusted_ble_detection_enabled;
bool trusted_ble_present;
bool unknown_wifi_alert;
bool unknown_wifi_detection_enabled;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(alarm_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(current_time, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(device_health_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency_authority_message_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency_escalation_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(heartbeat_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_alert_time, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_event, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_event_type, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_heartbeat_time, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_unknown_mac, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notification_channel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notification_event_type, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notification_sent_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photo_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sos_authority_note, READWRITE, ON_CHANGE, onSosAuthorityNoteChange);
  ArduinoCloud.addProperty(sos_message, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trusted_device_source, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ultrasonic_distance, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(auto_arm_hour, READWRITE, ON_CHANGE, onAutoArmHourChange);
  ArduinoCloud.addProperty(auto_arm_minute, READWRITE, ON_CHANGE, onAutoArmMinuteChange);
  ArduinoCloud.addProperty(auto_disarm_hour, READWRITE, ON_CHANGE, onAutoDisarmHourChange);
  ArduinoCloud.addProperty(auto_disarm_minute, READWRITE, ON_CHANGE, onAutoDisarmMinuteChange);
  ArduinoCloud.addProperty(current_hour, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(demo_scenario, READWRITE, ON_CHANGE, onDemoScenarioChange);
  ArduinoCloud.addProperty(event_counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(intrusion_score, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ldr_delta, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(ldr_value, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(rearm_countdown_remaining, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rearm_delay_seconds, READWRITE, ON_CHANGE, onRearmDelaySecondsChange);
  ArduinoCloud.addProperty(sensitivity_level, READWRITE, ON_CHANGE, onSensitivityLevelChange);
  ArduinoCloud.addProperty(threat_level, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trusted_ble_last_seen_seconds, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trusted_ble_rssi, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(unknown_wifi_count, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(alarm_enabled, READWRITE, ON_CHANGE, onAlarmEnabledChange);
  ArduinoCloud.addProperty(auto_capture_photo_request, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(buzzer_on, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cooldown_active, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(critical_security_compromise, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(demo_mode, READWRITE, ON_CHANGE, onDemoModeChange);
  ArduinoCloud.addProperty(device_tampered, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency_confirmation_requested, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency_confirmed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(home_address_configured, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(intrusion_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(known_device_present, READWRITE, ON_CHANGE, onKnownDevicePresentChange);
  ArduinoCloud.addProperty(ldr_covered, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_green_on, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_red_on, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light_abnormal, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manual_capture_photo, READWRITE, ON_CHANGE, onManualCapturePhotoChange);
  ArduinoCloud.addProperty(night_mode, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(object_near, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pet_detected, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pir_detected, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(reset_alarm, READWRITE, ON_CHANGE, onResetAlarmChange);
  ArduinoCloud.addProperty(sabotage_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(schedule_enabled, READWRITE, ON_CHANGE, onScheduleEnabledChange);
  ArduinoCloud.addProperty(send_notification_request, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sos_adult, READWRITE, ON_CHANGE, onSosAdultChange);
  ArduinoCloud.addProperty(sos_child, READWRITE, ON_CHANGE, onSosChildChange);
  ArduinoCloud.addProperty(system_armed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trusted_ble_detection_enabled, READWRITE, ON_CHANGE, onTrustedBleDetectionEnabledChange);
  ArduinoCloud.addProperty(trusted_ble_present, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(unknown_wifi_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(unknown_wifi_detection_enabled, READWRITE, ON_CHANGE, onUnknownWifiDetectionEnabledChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
