#pragma once

// Replace every placeholder locally. Do not commit arduino_secrets.h.
#define SECRET_SSID "YOUR_WIFI_SSID"
#define SECRET_OPTIONAL_PASS "YOUR_WIFI_PASSWORD"
#define SECRET_DEVICE_KEY "YOUR_ARDUINO_CLOUD_DEVICE_KEY"
#define SECRET_DEVICE_NAME "YOUR_ARDUINO_CLOUD_DEVICE_NAME"
#define SECRET_DEVICE_LOCATION "YOUR_ARDUINO_CLOUD_DEVICE_LOCATION"
#define SECRET_TELEGRAM_BOT_TOKEN "YOUR_TELEGRAM_BOT_TOKEN"
#define SECRET_TELEGRAM_CHAT_ID "YOUR_TELEGRAM_CHAT_ID"
#define SECRET_GEMINI_API_KEY "YOUR_OPTIONAL_GEMINI_API_KEY"
#define SECRET_GOOGLE_SCRIPT_URL "YOUR_PRIVATE_APPS_SCRIPT_URL"
