// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "20c65f7e-3a23-4472-8634-3df4df3e8a76";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSosAuthorityNoteChange();
void onAutoArmHourChange();
void onAutoArmMinuteChange();
void onAutoDisarmHourChange();
void onAutoDisarmMinuteChange();
void onSensitivityLevelChange();
void onAlarmEnabledChange();
void onAutoPhotoOnAlertChange();
void onCameraEnabledChange();
void onGeminiEnabledChange();
void onGoogleScriptEnabledChange();
void onHeartbeatEnabledChange();
void onManualCapturePhotoChange();
void onResetAlarmChange();
void onScheduleEnabledChange();
void onSosAdultChange();
void onSosChildChange();
void onTelegramEnabledChange();

String alarm_status;
String current_time;
String device_health_status;
String emergency_authority_message_status;
String emergency_escalation_status;
String heartbeat_status;
String last_event;
String last_heartbeat_time;
String notification_sent_status;
String photo_status;
String sos_authority_note;
int auto_arm_hour;
int auto_arm_minute;
int auto_disarm_hour;
int auto_disarm_minute;
int sensitivity_level;
bool alarm_enabled;
bool auto_photo_on_alert;
bool camera_enabled;
bool critical_security_compromise;
bool gemini_enabled;
bool google_script_enabled;
bool heartbeat_enabled;
bool home_address_configured;
bool intrusion_alert;
bool manual_capture_photo;
bool reset_alarm;
bool sabotage_alert;
bool schedule_enabled;
bool sos_adult;
bool sos_child;
bool system_armed;
bool telegram_enabled;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(alarm_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(current_time, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(device_health_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency_authority_message_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency_escalation_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(heartbeat_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_event, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(last_heartbeat_time, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notification_sent_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photo_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sos_authority_note, READWRITE, ON_CHANGE, onSosAuthorityNoteChange);
  ArduinoCloud.addProperty(auto_arm_hour, READWRITE, ON_CHANGE, onAutoArmHourChange);
  ArduinoCloud.addProperty(auto_arm_minute, READWRITE, ON_CHANGE, onAutoArmMinuteChange);
  ArduinoCloud.addProperty(auto_disarm_hour, READWRITE, ON_CHANGE, onAutoDisarmHourChange);
  ArduinoCloud.addProperty(auto_disarm_minute, READWRITE, ON_CHANGE, onAutoDisarmMinuteChange);
  ArduinoCloud.addProperty(sensitivity_level, READWRITE, ON_CHANGE, onSensitivityLevelChange);
  ArduinoCloud.addProperty(alarm_enabled, READWRITE, ON_CHANGE, onAlarmEnabledChange);
  ArduinoCloud.addProperty(auto_photo_on_alert, READWRITE, ON_CHANGE, onAutoPhotoOnAlertChange);
  ArduinoCloud.addProperty(camera_enabled, READWRITE, ON_CHANGE, onCameraEnabledChange);
  ArduinoCloud.addProperty(critical_security_compromise, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gemini_enabled, READWRITE, ON_CHANGE, onGeminiEnabledChange);
  ArduinoCloud.addProperty(google_script_enabled, READWRITE, ON_CHANGE, onGoogleScriptEnabledChange);
  ArduinoCloud.addProperty(heartbeat_enabled, READWRITE, ON_CHANGE, onHeartbeatEnabledChange);
  ArduinoCloud.addProperty(home_address_configured, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(intrusion_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manual_capture_photo, READWRITE, ON_CHANGE, onManualCapturePhotoChange);
  ArduinoCloud.addProperty(reset_alarm, READWRITE, ON_CHANGE, onResetAlarmChange);
  ArduinoCloud.addProperty(sabotage_alert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(schedule_enabled, READWRITE, ON_CHANGE, onScheduleEnabledChange);
  ArduinoCloud.addProperty(sos_adult, READWRITE, ON_CHANGE, onSosAdultChange);
  ArduinoCloud.addProperty(sos_child, READWRITE, ON_CHANGE, onSosChildChange);
  ArduinoCloud.addProperty(system_armed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(telegram_enabled, READWRITE, ON_CHANGE, onTelegramEnabledChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
